---
title: "BIOST 540 Project EDA"
output:
  html_document:
    df_print: paged
date: "2024-04-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(rigr)
```

```{r, echo=FALSE}
birthwt <- read_csv('cdc birthwt.csv')
```
Summary statistics for maternal age and infant birth weight by birth order
```{r}
birthwt %>% 
  group_by(border) %>%
  summarize(min(mage), median(mage), mean(mage), max(mage), min(bweight), median(bweight), mean(bweight), max(bweight))
```
```{r}
birthwt <- birthwt %>%
  arrange(mid, border) %>%
  group_by(mid) %>%
  mutate(last.mage = lag(mage),
         inter.mage = mage - lag(mage),
         last.bweight = lag(bweight),
         inter.bweight = bweight - lag(bweight))

birthwt %>% 
  group_by(border) %>%
  summarize(min(inter.mage), median(inter.mage), mean(inter.mage), max(inter.mage), min(inter.bweight), median(inter.bweight), mean(inter.bweight), max(inter.bweight))

birthwt_range <- birthwt %>%
  group_by(mid) %>%
  filter(border == 1 | border == 5) %>%
  arrange(mid, border) %>%
  mutate(range.mage = mage -lag(mage),
         range.bweight = bweight - lag(bweight))
```

